services:
  postgres:
    image: postgres:16-alpine
    container_name: bed_occupancy_postgres
    environment:
      POSTGRES_USER: de_user
      POSTGRES_PASSWORD: de_password
      POSTGRES_DB: hospital_dw
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U de_user -d hospital_dw"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
